"""Unified Triage stage for the osoji v1 architecture (V1-3).

Triage is the single evidence-weighted verifier that replaces osoji's six+
scattered per-detector verification gates. It consumes a batch of self-sufficient
:class:`Claim`s — :class:`~osoji.findings.Finding`s whose :class:`~osoji.evidence.Evidence`
has been assembled by a Claim Builder — and fills each finding's triage outputs
(``verdict`` / ``confidence`` / ``triage_reasoning`` / ``suggested_fix`` / ``severity``).

See ``osojicode/wiki`` ``specs/0001-v1-foundation.md`` (*The Triage stage (B)*),
``concepts/self-sufficient-claims.md``, ``concepts/three-gap-theory.md``, and
``concepts/string-contract-taxonomy.md``.

Two modes:

- **claim mode** (default): one forced-tool LLM call decides the whole batch.
  Bounded token cost — no exploration. The production path.
- **exploration mode**: a per-claim multi-turn loop where the LLM is given
  read-only ``read_file`` / ``grep`` / ``list_dir`` tools (see
  :class:`~osoji.triage_exec.ExplorationExecutor`) and decides with retrieval.
  Used by the V1-4 Claim-Builder bootstrap and by per-claim escalation.

The **rubric is an input prompt**, not baked into the stage: ``decide_batch``
takes a ``system_prompt``. V1-3 ships the canonical unified rubric
(:data:`TRIAGE_SYSTEM_PROMPT`) but the Phase 3 debris cutover passes the
preserved legacy prompt (:data:`DEBRIS_TRIAGE_SYSTEM_PROMPT`) so verdicts cannot
drift — the cutover is pure re-plumbing. Flipping debris onto the unified rubric
is a later, deliberate, measured change (V1-5).

Incremental-audit hook (V1-9): ``decide_batch`` accepts an optional verdict cache
keyed by ``(finding.id, evidence_fingerprint)``. A claim whose key hits the cache
reuses the cached verdict and **skips the LLM**. A ``None`` evidence_fingerprint is
cache-ineligible (always triaged) — never a key value — so two no-fingerprint
findings that collide on ``id`` cannot reuse a stale verdict.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from typing import Any

from .config import Config
from .evidence import Evidence
from .findings import Finding
from .llm.runtime import create_runtime
from .llm.types import CompletionOptions, Message, MessageRole
from .tools import (
    get_triage_claim_tool_definitions,
    get_triage_exploration_tool_definitions,
)
from .triage_exec import ExplorationExecutor

# Categories of debris finding whose claim-mode prompt is the preserved legacy
# debris-verify prompt (decision 2: re-plumbing, not re-rubric).
DEBRIS_TRIAGE_SYSTEM_PROMPT = """\
You are a code quality auditor verifying whether code debris findings are genuine or false positives.

Each finding was generated by analyzing a single file in isolation. You are now given cross-file
evidence from the project's facts database. Your job is to determine whether the cross-file
references represent genuine usage of the flagged symbol/field.

Guidelines:
- An import that accesses or sets the flagged field/symbol = genuine usage → DISMISS
- A call to the flagged function from another module = genuine usage → DISMISS
- A comment mentioning the name, a string literal with the same text, or a different
  symbol that happens to share the name = NOT genuine usage → CONFIRM the finding
- If references are ambiguous, lean toward CONFIRMING (keep the finding)
- For latent_bug findings: check whether cross-file evidence shows the type actually HAS
  the accessed attribute/method. If evidence confirms the attribute exists, DISMISS.
  If evidence is absent or ambiguous, CONFIRM.
- For union/sum types (e.g., TypeScript `A | B`, Python `Union[A, B]`), check whether
  the NARROWED variant (after a discriminant guard or early return) has the attribute —
  not whether the full union type has it. If the code checks a discriminant field and
  then accesses a member specific to the narrowed variant, DISMISS the finding.
- When type/class definition source code is provided, use it as authoritative
  evidence of the type's fields, methods, and default values.

Provide a verdict for EVERY finding listed."""


# The canonical unified rubric — three-gap predicates + gap-type guidance + the
# five-class string-contract sub-rubric. This is the spec's single largest
# optimization target. It is exercised by exploration mode and unit tests in
# V1-3; the debris production path migrates onto it in V1-5 with measurement.
TRIAGE_SYSTEM_PROMPT = """\
You are osoji's Triage stage: the single verifier for every code-quality finding.

Every finding is a hypothesis about a GAP between what the code claims and what it does:
- reachability — declared/claimed to be used, but actually unreachable
  (dead code, dead parameters, unactuated config, orphaned files, unused deps).
- description — described one way (comment, docstring, name, type), behaves another
  (stale comments, misleading docstrings, latent bugs that violate a stated contract).
- contract — an implicit cross-component agreement (shared string, schema, ABI) is broken
  (obligation violations, cross-file string drift).
- uncategorized — does not fit cleanly; decide on the merits and say so.

A finding is a TRUE POSITIVE iff all three predicates hold:
- Reality — the gap actually exists in the code (the evidence supports it).
- Significance — closing the gap improves the codebase; widening it would harm.
- Actionability — there is a concrete fix.
Confirm only when all three hold. Dismiss when any fails. Use 'uncertain' when the
assembled evidence genuinely cannot decide.

Weigh the assembled evidence. For reachability claims, a cross-file reference that is a
real import/call/use refutes the gap (dismiss); a reference that is only a comment, a
string literal, or a same-named-but-different symbol does not (confirm). Account for
dynamic dispatch, framework registration, re-exports, and within-file transitive liveness.

For contract gaps over hard-coded literals, classify the literal before deciding:
- Named project obligation — a constant exists; another site duplicates its bare literal.
  Confirm; suggest using the existing constant.
- Unnamed project obligation — two sites share a bare literal in clearly-related roles, no
  constant yet. Confirm; suggest extracting a shared constant.
- Ecosystem convention — meaning defined outside the project (HTTP codes, file modes,
  MIME types, RFC strings). Dismiss; the contract is with the external standard.
- Magic-constant duplication (ambiguous) — examine: confirm if the sites should agree,
  dismiss if coincidental.
- Coincidental duplication — same literal, unrelated roles. Dismiss as coincidence.

Capture your reasoning verbatim. Provide a verdict for EVERY claim."""


@dataclass
class Claim:
    """A self-sufficient claim: a Finding plus the escalation flag.

    Thin by design — the Evidence lives on ``finding.evidence`` (the V1-2 schema
    field), so V1-4's mechanized Claim Builder populates the same place. The
    ``insufficient_evidence`` flag marks a claim the Claim Builder could not fill;
    Triage escalates it to exploration mode only when escalation is enabled (off
    in the V1-3 production debris path — decision 1).
    """

    finding: Finding
    insufficient_evidence: bool = False


@dataclass
class TriageBatchResult:
    """Outcome of a :meth:`Triage.decide_batch` call."""

    findings: list[Finding]
    input_tokens: int = 0
    output_tokens: int = 0
    verdict_cache_hit_rate: float = 0.0
    would_escalate_count: int = 0
    exploration_traces: list[dict[str, Any]] = field(default_factory=list)


# Hard ceiling on exploration turns per claim, so a runaway loop can't spend
# unbounded tokens. Reaching it yields an 'uncertain' verdict.
_MAX_EXPLORATION_TURNS = 8


class Triage:
    """The unified Triage stage.

    A provider may be injected (tests); otherwise one is created per
    ``decide_batch`` call via :func:`create_runtime` and closed afterwards.
    """

    def __init__(
        self,
        config: Config,
        rate_limiter: Any | None = None,
        *,
        executor: ExplorationExecutor | None = None,
        provider: Any | None = None,
    ) -> None:
        self.config = config
        self.rate_limiter = rate_limiter
        self.executor = executor or ExplorationExecutor(config)
        self._provider = provider

    async def decide_batch(
        self,
        claims: list[Claim],
        *,
        mode: str = "claim",
        system_prompt: str = TRIAGE_SYSTEM_PROMPT,
        verdict_cache: dict[tuple[str, str], dict] | None = None,
        escalate_insufficient: bool = False,
    ) -> TriageBatchResult:
        """Decide a batch of claims, filling each finding's triage outputs.

        - ``mode="claim"``: non-cache, non-escalated claims are decided by one
          batched LLM call.
        - ``mode="exploration"``: every non-cache claim is decided by a per-claim
          exploration loop.
        - Cache hits (non-None fingerprint whose ``(id, fingerprint)`` is in
          ``verdict_cache``) reuse the cached verdict and skip the LLM.
        - ``insufficient_evidence`` claims escalate to exploration only when
          ``escalate_insufficient`` is True; otherwise they pass through
          unverified (verdict stays ``None``). The count is always reported.
        """

        n = len(claims)
        findings: list[Finding] = [c.finding for c in claims]
        would_escalate = sum(1 for c in claims if c.insufficient_evidence)
        cache = verdict_cache or {}
        cache_hits = 0

        claim_route: list[tuple[int, Claim]] = []
        explore_route: list[tuple[int, Claim]] = []
        for idx, claim in enumerate(claims):
            fp = claim.finding.evidence_fingerprint
            if fp is not None and (claim.finding.id, fp) in cache:
                findings[idx] = _apply_cached(claim.finding, cache[(claim.finding.id, fp)])
                cache_hits += 1
                continue
            if mode == "exploration":
                explore_route.append((idx, claim))
            elif claim.insufficient_evidence:
                if escalate_insufficient:
                    explore_route.append((idx, claim))
                # else: pass-through, verdict stays None (decision 1)
            else:
                claim_route.append((idx, claim))

        in_tok = out_tok = 0
        traces: list[dict[str, Any]] = []

        if claim_route or explore_route:
            provider, owns = self._get_provider()
            try:
                if claim_route:
                    decided, ti, to = await self._run_claim_batch(
                        [c for _, c in claim_route], system_prompt, provider
                    )
                    for (idx, _), fnd in zip(claim_route, decided):
                        findings[idx] = fnd
                    in_tok += ti
                    out_tok += to
                for idx, claim in explore_route:
                    fnd, ti, to, trace = await self._run_exploration(
                        claim, system_prompt, provider
                    )
                    findings[idx] = fnd
                    in_tok += ti
                    out_tok += to
                    traces.append(trace)
            finally:
                if owns:
                    await provider.close()

        hit_rate = cache_hits / n if n else 0.0
        return TriageBatchResult(
            findings=findings,
            input_tokens=in_tok,
            output_tokens=out_tok,
            verdict_cache_hit_rate=hit_rate,
            would_escalate_count=would_escalate,
            exploration_traces=traces,
        )

    # -- provider ----------------------------------------------------------

    def _get_provider(self) -> tuple[Any, bool]:
        """Return (provider, owns). Injected providers are not owned/closed."""

        if self._provider is not None:
            return self._provider, False
        provider, _ = create_runtime(self.config, rate_limiter=self.rate_limiter)
        return provider, True

    # -- claim mode --------------------------------------------------------

    async def _run_claim_batch(
        self, claims: list[Claim], system_prompt: str, provider: Any
    ) -> tuple[list[Finding], int, int]:
        n = len(claims)
        user = self._render_claim_batch(claims)

        def check_completeness(tool_name: str, tool_input: dict) -> list[str]:
            if tool_name != "submit_triage_verdicts":
                return []
            got = {v.get("batch_index") for v in tool_input.get("verdicts", [])}
            return [f"Missing verdict for batch_index {i}" for i in range(n) if i not in got]

        result = await provider.complete(
            messages=[Message(role=MessageRole.USER, content=user)],
            system=system_prompt,
            options=CompletionOptions(
                model=self.config.model_for("medium"),
                max_tokens=max(512, n * 200),
                reservation_key="audit.triage",
                tools=get_triage_claim_tool_definitions(),
                tool_choice={"type": "tool", "name": "submit_triage_verdicts"},
                tool_input_validators=[check_completeness],
            ),
        )

        verdict_by_index: dict[int, dict] = {}
        for tc in result.tool_calls:
            if tc.name == "submit_triage_verdicts":
                for v in tc.input.get("verdicts", []):
                    bi = v.get("batch_index")
                    if bi is not None:
                        verdict_by_index[bi] = v

        decided = [
            _apply_verdict(c.finding, verdict_by_index[i]) if i in verdict_by_index else c.finding
            for i, c in enumerate(claims)
        ]
        return decided, result.input_tokens, result.output_tokens

    def _render_claim_batch(self, claims: list[Claim]) -> str:
        parts = ["## Claims to triage\n"]
        for i, claim in enumerate(claims):
            parts.append(self._render_claim_block(i, claim.finding))
        parts.append(
            f"\nProvide a verdict for EVERY claim (batch indices 0..{len(claims) - 1}) "
            "using the submit_triage_verdicts tool."
        )
        return "\n".join(parts)

    @staticmethod
    def _render_claim_block(index: int, finding: Finding) -> str:
        loc = finding.path
        if finding.line_start:
            loc += f":L{finding.line_start}-{finding.line_end}"
        lines = [f"### Claim {index}: {finding.detector} [{finding.gap_type}] — {loc}"]
        if finding.symbol:
            lines.append(f"Symbol: `{finding.symbol}`")
        lines.append(f"Claim ({finding.contract_source}): {finding.contract_claim}")
        lines.append(f"Observed: {finding.observed_behavior}")
        if finding.evidence:
            lines.append("Evidence:")
            for ev in finding.evidence:
                lines.append(_render_evidence(ev))
        lines.append("")
        return "\n".join(lines)

    # -- exploration mode (implemented in V1-3 task #5) --------------------

    async def _run_exploration(
        self, claim: Claim, system_prompt: str, provider: Any
    ) -> tuple[Finding, int, int, dict[str, Any]]:
        """Decide one claim via a multi-turn read/grep/list loop.

        The model is given the claim plus read-only retrieval tools and a terminal
        ``submit_triage_verdict`` tool. Every tool call is recorded to the trace
        (for V1-4 mining). Reaching the turn limit without a verdict yields
        ``uncertain``. Tool results are fed back as Anthropic content blocks — the
        provider passes ``Message.content`` straight through (see
        ``llm/anthropic.py``), so assistant ``tool_use`` and user ``tool_result``
        blocks round-trip without a dedicated message role.
        """

        finding = claim.finding
        user = (
            self._render_claim_block(0, finding)
            + "\nExplore the repository with read_file / grep / list_dir as needed, "
            "then call submit_triage_verdict with your decision."
        )
        messages: list[Message] = [Message(role=MessageRole.USER, content=user)]
        trace: dict[str, Any] = {"finding_id": finding.id, "calls": []}
        tools = get_triage_exploration_tool_definitions()
        in_tok = out_tok = 0
        verdict: dict | None = None

        for turn in range(_MAX_EXPLORATION_TURNS):
            result = await provider.complete(
                messages=messages,
                system=system_prompt,
                options=CompletionOptions(
                    model=self.config.model_for("medium"),
                    max_tokens=2048,
                    reservation_key="audit.triage.explore",
                    tools=tools,
                    tool_choice={"type": "auto"},
                ),
            )
            in_tok += result.input_tokens
            out_tok += result.output_tokens
            if not result.tool_calls:
                break  # model answered in prose / gave up

            assistant_content: list[dict[str, Any]] = []
            if result.content:
                assistant_content.append({"type": "text", "text": result.content})
            for tc in result.tool_calls:
                assistant_content.append(
                    {"type": "tool_use", "id": tc.id, "name": tc.name, "input": tc.input}
                )
            messages.append(Message(role=MessageRole.ASSISTANT, content=assistant_content))

            for tc in result.tool_calls:
                trace["calls"].append({"turn": turn, "name": tc.name, "input": tc.input})
                if tc.name == "submit_triage_verdict":
                    verdict = tc.input
            if verdict is not None:
                break

            tool_results = [
                {
                    "type": "tool_result",
                    "tool_use_id": tc.id,
                    "content": self.executor.run(tc.name, tc.input),
                }
                for tc in result.tool_calls
            ]
            messages.append(Message(role=MessageRole.USER, content=tool_results))

        if verdict is not None:
            decided = _apply_verdict(finding, verdict)
        else:
            decided = replace(
                finding,
                verdict="uncertain",
                confidence=0.0,
                triage_reasoning="Exploration did not produce a verdict within the turn limit.",
            )
        return decided, in_tok, out_tok, trace


# -- module helpers --------------------------------------------------------


def _apply_verdict(finding: Finding, v: dict) -> Finding:
    """Return a copy of ``finding`` with triage outputs from a verdict dict."""

    return replace(
        finding,
        verdict=v.get("verdict"),
        confidence=v.get("confidence"),
        triage_reasoning=v.get("reasoning"),
        suggested_fix=v.get("suggested_fix"),
        severity=v.get("severity"),
    )


def _apply_cached(finding: Finding, cached: dict) -> Finding:
    """Return a copy of ``finding`` with triage outputs from a cache entry."""

    return replace(
        finding,
        verdict=cached.get("verdict"),
        confidence=cached.get("confidence"),
        triage_reasoning=cached.get("triage_reasoning"),
        suggested_fix=cached.get("suggested_fix"),
        severity=cached.get("severity"),
    )


def _render_evidence(ev: Evidence) -> str:
    """Render a single Evidence into the claim prompt (positional, not semantic)."""

    if ev.kind == "cross_file_reference":
        references = ev.payload.get("references", [])
        scope = ev.payload.get("scan_scope")
        out = []
        if references:
            out.append("Cross-file references:")
            for ref in references:
                resolves = " (resolves to source)" if ref.get("resolves_to_source") else ""
                same_file = " (same file, outside the flagged region)" if ref.get("same_file") else ""
                line = f":{ref['line']}" if ref.get("line") else ""
                out.append(
                    f"- `{ref.get('file')}{line}` [{ref.get('kind')}]{same_file}: "
                    f"{ref.get('context')}{resolves}"
                )
            if scope:
                out.append(
                    f"(reference sweep covered {scope.get('files_scanned')} files "
                    f"for: {', '.join(scope.get('needles', []))})"
                )
        elif scope:
            # Evidence-of-absence: state it explicitly — the canonical case-FOR
            # a reachability claim is the zero-hit sweep with honest scope.
            swept = (
                "including the flagged file outside the flagged region"
                if scope.get("same_file_swept")
                else "outside the flagged file"
            )
            out.append(
                f"No references found: {scope.get('files_scanned')} files swept "
                f"for {', '.join(scope.get('needles', []))} — zero matches, {swept}."
            )
        surface = ev.payload.get("export_surface")
        if surface:
            exported = "IS" if surface.get("exported_from_flagged_file") else "is NOT"
            out.append(
                f"Export surface: `{surface.get('symbol')}` {exported} part of the "
                "flagged file's export list (exported symbols may have consumers "
                "outside this repository)."
            )
        for file, excerpt in (ev.payload.get("shadow_excerpts") or {}).items():
            out.append(f"Shadow doc for `{file}`:\n{excerpt}")
        if out:
            return "\n".join(out)
        return "Cross-file references: none gathered."
    if ev.kind == "surrounding_code":
        p = ev.payload
        out = [
            f"Surrounding code `{p.get('file')}` "
            f"L{p.get('line_start')}-{p.get('line_end')} (anchor: {p.get('anchor')}):"
        ]
        enclosing = p.get("enclosing_symbol")
        if enclosing:
            out.append(
                f"Enclosing {enclosing.get('kind')} `{enclosing.get('name')}` "
                f"(L{enclosing.get('line_start')}-{enclosing.get('line_end')})"
            )
        out.append(f"```\n{p.get('snippet', '')}\n```")
        return "\n".join(out)
    if ev.kind == "declared_intent":
        p = ev.payload
        out = [f"Declared intent near the flagged region of `{p.get('file')}`:"]
        for block in p.get("blocks", []):
            symbol = f" of `{block['symbol']}`" if block.get("symbol") else ""
            out.append(
                f"[{block.get('label')}{symbol}, from L{block.get('line_start')}]\n"
                f"{block.get('text', '')}"
            )
        return "\n".join(out)
    if ev.kind == "type_signature":
        p = ev.payload
        return f"Type `{p.get('type_name')}` defined in `{p.get('file')}`:\n```\n{p.get('source', '')}\n```"
    if ev.kind == "shadow_doc_claim":
        p = ev.payload
        scope = f" ({p['scope']} scope)" if p.get("scope") else ""
        body = p.get("excerpt") or p.get("content", "")
        return f"Shadow doc `{p.get('file')}`{scope}:\n{body}"
    return json.dumps(ev.payload, ensure_ascii=False, default=str)
