"""V1-5e debris rubric A/B (osojicode/work#52).

Replays the live ``.osoji/findings/`` debris corpus through the unified
Triage stage twice — identical claims, identical evidence, identical code;
the ONLY variable is ``system_prompt``:

  side A: DEBRIS_TRIAGE_SYSTEM_PROMPT  (legacy rubric, current production)
  side B: TRIAGE_SYSTEM_PROMPT         (unified tri-section rubric)

Mirrors production Phase 3 (audit.py:_run_phase3_async): one claim-mode
``decide_batch`` call over the full eligible claim set. The impl-hash
staleness gate is bypassed exactly as in measure_debris_cutover.py — this
branch changes source, so the pre-branch sidecars would otherwise all read
as stale; both sides see identical inputs, so the gate is irrelevant to the
comparison.

Usage (from the branch worktree; --root points at a checkout holding the
corpus in .osoji/):

    PYTHONUTF8=1 python scripts/ab_v15e_debris_rubric.py \
        --root C:/Users/johnf/projects/osoji \
        --out scratch/ab-v15e-raw.json
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from dotenv import load_dotenv  # noqa: E402

from osoji.claim_builder import build_debris_claims  # noqa: E402
from osoji.config import Config  # noqa: E402
from osoji.llm.runtime import create_runtime  # noqa: E402
from osoji.triage import TRIAGE_SYSTEM_PROMPT, Triage  # noqa: E402

# Frozen copy of the legacy prompt this A/B retired (removed from triage.py by
# the V1-5e flip) so the gate script stays runnable as a historical artifact.
DEBRIS_TRIAGE_SYSTEM_PROMPT = """\
You are a code quality auditor verifying whether code debris findings are genuine or false positives.

Each finding was generated by analyzing a single file in isolation. You are now given cross-file
evidence from the project's facts database. Your job is to determine whether the cross-file
references represent genuine usage of the flagged symbol/field.

Guidelines:
- An import that accesses or sets the flagged field/symbol = genuine usage → DISMISS
- A call to the flagged function from another module = genuine usage → DISMISS
- A comment mentioning the name, a string literal with the same text, or a different
  symbol that happens to share the name = NOT genuine usage → CONFIRM the finding
- If references are ambiguous, lean toward CONFIRMING (keep the finding)
- For latent_bug findings: check whether cross-file evidence shows the type actually HAS
  the accessed attribute/method. If evidence confirms the attribute exists, DISMISS.
  If evidence is absent or ambiguous, CONFIRM.
- For union/sum types (e.g., TypeScript `A | B`, Python `Union[A, B]`), check whether
  the NARROWED variant (after a discriminant guard or early return) has the attribute —
  not whether the full union type has it. If the code checks a discriminant field and
  then accesses a member specific to the narrowed variant, DISMISS the finding.
- When type/class definition source code is provided, use it as authoritative
  evidence of the type's fields, methods, and default values.

Provide a verdict for EVERY finding listed."""

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from measure_debris_cutover import load_debris_ignoring_impl_hash  # noqa: E402


def _finding_row(finding) -> dict:
    return {
        "id": finding.id,
        "detector": finding.detector,
        "path": finding.path,
        "symbol": finding.symbol,
        "line_start": finding.line_start,
        "line_end": finding.line_end,
        "contract_claim": finding.contract_claim,
        "verdict": finding.verdict,
        "confidence": finding.confidence,
        "severity": finding.severity,
        "reasoning": finding.triage_reasoning,
        "suggested_fix": finding.suggested_fix,
    }


async def _run_side(label: str, claims, config: Config, system_prompt: str) -> dict:
    """Decide the claims in production-bounded chunks.

    Uses ``decide_junk_claims`` (BATCH_SIZE=12, same-file adjacency, bisect on
    failure) rather than one monolithic ``decide_batch`` call: the first
    single-batch run of this A/B produced an off-by-one verdict misalignment
    on side B that the symbol-echo validator could not catch because debris
    claims carry ``symbol=None`` (see the run-1 addendum in
    ab-v15e-report.md). Chunking both sides identically keeps the prompt as
    the single variable.
    """

    from osoji.junk_triage import decide_junk_claims

    provider, _ = create_runtime(config)
    try:
        findings, in_tok, out_tok = await decide_junk_claims(
            list(claims), config, provider, system_prompt=system_prompt
        )
    finally:
        await provider.close()
    undecided = sum(1 for f in findings if f.verdict is None)
    print(
        f"[{label}] {len(findings)} findings decided, {undecided} undecided, "
        f"tokens {in_tok}^ {out_tok}v",
        flush=True,
    )
    return {
        "input_tokens": in_tok,
        "output_tokens": out_tok,
        "undecided": undecided,
        "findings": [_finding_row(f) for f in findings],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", required=True, help="checkout holding .osoji/ with the corpus")
    parser.add_argument("--out", default="scratch/ab-v15e-raw.json")
    args = parser.parse_args()

    load_dotenv(Path(args.root) / ".env")

    config = Config(
        root_path=Path(args.root),
        provider="anthropic",
        respect_gitignore=False,
        quiet=True,
    )
    raw_debris = load_debris_ignoring_impl_hash(config)
    claims, original_indices, would_escalate = build_debris_claims(config, raw_debris)
    print(
        f"corpus: {len(raw_debris)} raw debris findings, {len(claims)} eligible claims, "
        f"{would_escalate} would-escalate (kept unverified)",
        flush=True,
    )
    if not claims:
        raise SystemExit("no claims — corpus missing?")

    side_a = asyncio.run(_run_side("A legacy", claims, config, DEBRIS_TRIAGE_SYSTEM_PROMPT))
    side_b = asyncio.run(_run_side("B unified", claims, config, TRIAGE_SYSTEM_PROMPT))

    changed = []
    for row_a, row_b in zip(side_a["findings"], side_b["findings"]):
        assert row_a["id"] == row_b["id"]
        if row_a["verdict"] != row_b["verdict"]:
            changed.append({
                "id": row_a["id"],
                "detector": row_a["detector"],
                "path": row_a["path"],
                "symbol": row_a["symbol"],
                "lines": [row_a["line_start"], row_a["line_end"]],
                "claim": row_a["contract_claim"],
                "legacy": {k: row_a[k] for k in ("verdict", "confidence", "reasoning")},
                "unified": {k: row_b[k] for k in ("verdict", "confidence", "reasoning")},
            })

    out = {
        "corpus_size": len(claims),
        "would_escalate": would_escalate,
        "changed_verdict_count": len(changed),
        "changed": changed,
        "side_a_legacy": side_a,
        "side_b_unified": side_b,
    }
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"\nchanged verdicts: {len(changed)}/{len(claims)}")
    for ch in changed:
        print(f"  {ch['detector']} {ch['path']}:{ch['lines'][0]} {ch['symbol'] or ''}: "
              f"{ch['legacy']['verdict']} -> {ch['unified']['verdict']}")
    print(f"raw results: {out_path}")


if __name__ == "__main__":
    main()
